// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['updater']['UpdaterService']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['updater']['UpdaterService']['CheckForUpdate']();
}

export function GetCurrentVersion() {
  return window['go']['updater']['UpdaterService']['GetCurrentVersion']();
}

export function SetContext(arg1) {
  return window['go']['updater']['UpdaterService']['SetContext'](arg1);
}

export function StartPeriodicCheck() {
  return window['go']['updater']['UpdaterService']['StartPeriodicCheck']();
}
