// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {context} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function GetCurrentVersion():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartPeriodicCheck():Promise<void>;
