// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Configure(arg1) {
  return window['go']['schema']['SchemaService']['Configure'](arg1);
}

export function GetCompatibility(arg1) {
  return window['go']['schema']['SchemaService']['GetCompatibility'](arg1);
}

export function GetSchemaVersion(arg1, arg2) {
  return window['go']['schema']['SchemaService']['GetSchemaVersion'](arg1, arg2);
}

export function GetSchemaVersions(arg1) {
  return window['go']['schema']['SchemaService']['GetSchemaVersions'](arg1);
}

export function GetSubjects() {
  return window['go']['schema']['SchemaService']['GetSubjects']();
}

export function SetContext(arg1) {
  return window['go']['schema']['SchemaService']['SetContext'](arg1);
}
