// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {schema} from '../models';
import {context} from '../models';

export function Configure(arg1:string):Promise<void>;

export function GetCompatibility(arg1:string):Promise<string>;

export function GetSchemaVersion(arg1:string,arg2:number):Promise<schema.SchemaVersion>;

export function GetSchemaVersions(arg1:string):Promise<Array<schema.SchemaVersion>>;

export function GetSubjects():Promise<Array<schema.SchemaSubject>>;

export function SetContext(arg1:context.Context):Promise<void>;
