// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {templates} from '../models';
import {context} from '../models';

export function DeleteTemplate(arg1:string,arg2:string):Promise<void>;

export function ExportTemplates(arg1:string):Promise<string>;

export function ExportToFile(arg1:string):Promise<void>;

export function GetTemplate(arg1:string,arg2:string):Promise<templates.TopicTemplate>;

export function GetTemplates(arg1:string):Promise<Record<string, templates.TopicTemplate>>;

export function ImportFromFile(arg1:string,arg2:boolean):Promise<void>;

export function ImportTemplates(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveTemplate(arg1:string,arg2:templates.TopicTemplate):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateTemplate(arg1:string,arg2:string,arg3:templates.TopicTemplate):Promise<void>;
