// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTemplate(arg1, arg2) {
  return window['go']['templates']['TemplateService']['DeleteTemplate'](arg1, arg2);
}

export function ExportTemplates(arg1) {
  return window['go']['templates']['TemplateService']['ExportTemplates'](arg1);
}

export function ExportToFile(arg1) {
  return window['go']['templates']['TemplateService']['ExportToFile'](arg1);
}

export function GetTemplate(arg1, arg2) {
  return window['go']['templates']['TemplateService']['GetTemplate'](arg1, arg2);
}

export function GetTemplates(arg1) {
  return window['go']['templates']['TemplateService']['GetTemplates'](arg1);
}

export function ImportFromFile(arg1, arg2) {
  return window['go']['templates']['TemplateService']['ImportFromFile'](arg1, arg2);
}

export function ImportTemplates(arg1, arg2, arg3) {
  return window['go']['templates']['TemplateService']['ImportTemplates'](arg1, arg2, arg3);
}

export function SaveTemplate(arg1, arg2) {
  return window['go']['templates']['TemplateService']['SaveTemplate'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['templates']['TemplateService']['SetContext'](arg1);
}

export function UpdateTemplate(arg1, arg2, arg3) {
  return window['go']['templates']['TemplateService']['UpdateTemplate'](arg1, arg2, arg3);
}
