// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lagalert} from '../models';
import {context} from '../models';

export function AddRule(arg1:string,arg2:lagalert.AlertRule):Promise<void>;

export function ClearAlerts(arg1:string):Promise<void>;

export function DeleteRule(arg1:string,arg2:string):Promise<void>;

export function GetAlertConfig(arg1:string):Promise<lagalert.ClusterAlertConfig>;

export function GetAlerts(arg1:string):Promise<Array<lagalert.AlertEvent>>;

export function GetUnreadCount(arg1:string):Promise<number>;

export function MarkAllRead(arg1:string):Promise<void>;

export function RestartMonitoring(arg1:string):Promise<void>;

export function SaveAlertConfig(arg1:string,arg2:lagalert.ClusterAlertConfig):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function Stop():Promise<void>;

export function UpdateRule(arg1:string,arg2:lagalert.AlertRule):Promise<void>;
