// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['AddRule'](arg1, arg2);
}

export function ClearAlerts(arg1) {
  return window['go']['lagalert']['LagAlertService']['ClearAlerts'](arg1);
}

export function DeleteRule(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['DeleteRule'](arg1, arg2);
}

export function GetAlertConfig(arg1) {
  return window['go']['lagalert']['LagAlertService']['GetAlertConfig'](arg1);
}

export function GetAlerts(arg1) {
  return window['go']['lagalert']['LagAlertService']['GetAlerts'](arg1);
}

export function GetGroupTimeSeries(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['GetGroupTimeSeries'](arg1, arg2);
}

export function GetTopicTimeSeries(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['GetTopicTimeSeries'](arg1, arg2);
}

export function GetUnreadCount(arg1) {
  return window['go']['lagalert']['LagAlertService']['GetUnreadCount'](arg1);
}

export function MarkAllRead(arg1) {
  return window['go']['lagalert']['LagAlertService']['MarkAllRead'](arg1);
}

export function RestartMonitoring(arg1) {
  return window['go']['lagalert']['LagAlertService']['RestartMonitoring'](arg1);
}

export function SaveAlertConfig(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['SaveAlertConfig'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['lagalert']['LagAlertService']['SetContext'](arg1);
}

export function Start(arg1) {
  return window['go']['lagalert']['LagAlertService']['Start'](arg1);
}

export function Stop() {
  return window['go']['lagalert']['LagAlertService']['Stop']();
}

export function UpdateRule(arg1, arg2) {
  return window['go']['lagalert']['LagAlertService']['UpdateRule'](arg1, arg2);
}
