// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {annotations} from '../models';
import {context} from '../models';

export function BatchSetAnnotation(arg1:string,arg2:Array<string>,arg3:annotations.TopicAnnotation):Promise<void>;

export function DeleteAnnotation(arg1:string,arg2:string):Promise<void>;

export function ExportAllAnnotations():Promise<string>;

export function ExportAllToFile():Promise<void>;

export function ExportAnnotations(arg1:string):Promise<string>;

export function ExportToFile(arg1:string):Promise<void>;

export function GetAnnotation(arg1:string,arg2:string):Promise<annotations.TopicAnnotation>;

export function GetAnnotations(arg1:string):Promise<Record<string, annotations.TopicAnnotation>>;

export function GetServiceNames(arg1:string):Promise<Array<string>>;

export function ImportAnnotations(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ImportFromFile(arg1:string,arg2:boolean):Promise<void>;

export function SetAnnotation(arg1:string,arg2:string,arg3:annotations.TopicAnnotation):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
