// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchSetAnnotation(arg1, arg2, arg3) {
  return window['go']['annotations']['AnnotationService']['BatchSetAnnotation'](arg1, arg2, arg3);
}

export function DeleteAnnotation(arg1, arg2) {
  return window['go']['annotations']['AnnotationService']['DeleteAnnotation'](arg1, arg2);
}

export function ExportAllAnnotations() {
  return window['go']['annotations']['AnnotationService']['ExportAllAnnotations']();
}

export function ExportAllToFile() {
  return window['go']['annotations']['AnnotationService']['ExportAllToFile']();
}

export function ExportAnnotations(arg1) {
  return window['go']['annotations']['AnnotationService']['ExportAnnotations'](arg1);
}

export function ExportToFile(arg1) {
  return window['go']['annotations']['AnnotationService']['ExportToFile'](arg1);
}

export function GetAnnotation(arg1, arg2) {
  return window['go']['annotations']['AnnotationService']['GetAnnotation'](arg1, arg2);
}

export function GetAnnotations(arg1) {
  return window['go']['annotations']['AnnotationService']['GetAnnotations'](arg1);
}

export function GetServiceNames(arg1) {
  return window['go']['annotations']['AnnotationService']['GetServiceNames'](arg1);
}

export function ImportAnnotations(arg1, arg2, arg3) {
  return window['go']['annotations']['AnnotationService']['ImportAnnotations'](arg1, arg2, arg3);
}

export function ImportFromFile(arg1, arg2) {
  return window['go']['annotations']['AnnotationService']['ImportFromFile'](arg1, arg2);
}

export function SetAnnotation(arg1, arg2, arg3) {
  return window['go']['annotations']['AnnotationService']['SetAnnotation'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['annotations']['AnnotationService']['SetContext'](arg1);
}
