// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kafka} from '../models';
import {context} from '../models';

export function Connect(arg1:string):Promise<void>;

export function ConsumeMessages(arg1:string,arg2:number,arg3:number,arg4:number):Promise<Array<kafka.Message>>;

export function CreateTopic(arg1:string,arg2:number,arg3:number,arg4:Record<string, string>):Promise<void>;

export function DeleteTopic(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveCluster():Promise<string>;

export function GetBrokers():Promise<Array<kafka.Broker>>;

export function GetClusterHealth():Promise<kafka.ClusterHealth>;

export function GetConsumerGroupDetail(arg1:string):Promise<kafka.ConsumerGroupDetail>;

export function GetConsumerGroups():Promise<Array<kafka.ConsumerGroup>>;

export function GetTopic(arg1:string):Promise<kafka.Topic>;

export function GetTopicACLs(arg1:string):Promise<Array<kafka.AclEntry>>;

export function GetTopicConfigs(arg1:string):Promise<Array<kafka.TopicConfig>>;

export function GetTopicConsumers(arg1:string):Promise<Array<kafka.ConsumerGroup>>;

export function GetTopicPartitions(arg1:string):Promise<Array<kafka.Partition>>;

export function GetTopics():Promise<Array<kafka.Topic>>;

export function IsConnected():Promise<boolean>;

export function ProduceMessage(arg1:string,arg2:number,arg3:string,arg4:string,arg5:Record<string, string>):Promise<void>;

export function ResetConsumerGroupOffsets(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
