// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache() {
  return window['go']['kafka']['KafkaService']['ClearCache']();
}

export function Connect(arg1) {
  return window['go']['kafka']['KafkaService']['Connect'](arg1);
}

export function ConsumeMessages(arg1, arg2, arg3, arg4) {
  return window['go']['kafka']['KafkaService']['ConsumeMessages'](arg1, arg2, arg3, arg4);
}

export function ConsumeMessagesFromTimestamp(arg1, arg2, arg3, arg4) {
  return window['go']['kafka']['KafkaService']['ConsumeMessagesFromTimestamp'](arg1, arg2, arg3, arg4);
}

export function CreateTopic(arg1, arg2, arg3, arg4) {
  return window['go']['kafka']['KafkaService']['CreateTopic'](arg1, arg2, arg3, arg4);
}

export function DeleteRecordsBefore(arg1, arg2, arg3) {
  return window['go']['kafka']['KafkaService']['DeleteRecordsBefore'](arg1, arg2, arg3);
}

export function DeleteRecordsBeforeTimestamp(arg1, arg2) {
  return window['go']['kafka']['KafkaService']['DeleteRecordsBeforeTimestamp'](arg1, arg2);
}

export function DeleteTopic(arg1) {
  return window['go']['kafka']['KafkaService']['DeleteTopic'](arg1);
}

export function Disconnect() {
  return window['go']['kafka']['KafkaService']['Disconnect']();
}

export function GetActiveCluster() {
  return window['go']['kafka']['KafkaService']['GetActiveCluster']();
}

export function GetBrokers() {
  return window['go']['kafka']['KafkaService']['GetBrokers']();
}

export function GetClusterHealth() {
  return window['go']['kafka']['KafkaService']['GetClusterHealth']();
}

export function GetConsumerGroupDetail(arg1) {
  return window['go']['kafka']['KafkaService']['GetConsumerGroupDetail'](arg1);
}

export function GetConsumerGroups() {
  return window['go']['kafka']['KafkaService']['GetConsumerGroups']();
}

export function GetDashboardData() {
  return window['go']['kafka']['KafkaService']['GetDashboardData']();
}

export function GetTopic(arg1) {
  return window['go']['kafka']['KafkaService']['GetTopic'](arg1);
}

export function GetTopicACLs(arg1) {
  return window['go']['kafka']['KafkaService']['GetTopicACLs'](arg1);
}

export function GetTopicConfigs(arg1) {
  return window['go']['kafka']['KafkaService']['GetTopicConfigs'](arg1);
}

export function GetTopicConsumers(arg1) {
  return window['go']['kafka']['KafkaService']['GetTopicConsumers'](arg1);
}

export function GetTopicPartitions(arg1) {
  return window['go']['kafka']['KafkaService']['GetTopicPartitions'](arg1);
}

export function GetTopics() {
  return window['go']['kafka']['KafkaService']['GetTopics']();
}

export function IsConnected() {
  return window['go']['kafka']['KafkaService']['IsConnected']();
}

export function ProduceMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['kafka']['KafkaService']['ProduceMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ProduceMessages(arg1, arg2) {
  return window['go']['kafka']['KafkaService']['ProduceMessages'](arg1, arg2);
}

export function PurgeTopic(arg1) {
  return window['go']['kafka']['KafkaService']['PurgeTopic'](arg1);
}

export function ResetConsumerGroupOffsets(arg1, arg2) {
  return window['go']['kafka']['KafkaService']['ResetConsumerGroupOffsets'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['kafka']['KafkaService']['SetContext'](arg1);
}

export function StartLiveTail(arg1) {
  return window['go']['kafka']['KafkaService']['StartLiveTail'](arg1);
}

export function StopLiveTail() {
  return window['go']['kafka']['KafkaService']['StopLiveTail']();
}
