// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCluster(arg1) {
  return window['go']['config']['ConfigService']['DeleteCluster'](arg1);
}

export function DuplicateCluster(arg1) {
  return window['go']['config']['ConfigService']['DuplicateCluster'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['config']['ConfigService']['ExportConfig'](arg1);
}

export function GetActiveClusterID() {
  return window['go']['config']['ConfigService']['GetActiveClusterID']();
}

export function GetCluster(arg1) {
  return window['go']['config']['ConfigService']['GetCluster'](arg1);
}

export function GetClusters() {
  return window['go']['config']['ConfigService']['GetClusters']();
}

export function GetConfigDir() {
  return window['go']['config']['ConfigService']['GetConfigDir']();
}

export function GetDecryptedPassword(arg1) {
  return window['go']['config']['ConfigService']['GetDecryptedPassword'](arg1);
}

export function GetDecryptedSchemaRegistryPassword(arg1) {
  return window['go']['config']['ConfigService']['GetDecryptedSchemaRegistryPassword'](arg1);
}

export function GetSettings() {
  return window['go']['config']['ConfigService']['GetSettings']();
}

export function ImportConfig(arg1) {
  return window['go']['config']['ConfigService']['ImportConfig'](arg1);
}

export function ListAWSProfiles() {
  return window['go']['config']['ConfigService']['ListAWSProfiles']();
}

export function SaveCluster(arg1) {
  return window['go']['config']['ConfigService']['SaveCluster'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['config']['ConfigService']['SaveSettings'](arg1);
}

export function SetActiveCluster(arg1) {
  return window['go']['config']['ConfigService']['SetActiveCluster'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['config']['ConfigService']['TestConnection'](arg1);
}
