// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DeleteCluster(arg1:string):Promise<void>;

export function DuplicateCluster(arg1:string):Promise<config.ClusterProfile>;

export function ExportConfig(arg1:boolean):Promise<string>;

export function GetActiveClusterID():Promise<string>;

export function GetCluster(arg1:string):Promise<config.ClusterProfile>;

export function GetClusters():Promise<Array<config.ClusterProfile>>;

export function GetConfigDir():Promise<string>;

export function GetDecryptedPassword(arg1:string):Promise<string>;

export function GetDecryptedSchemaRegistryPassword(arg1:string):Promise<string>;

export function GetSettings():Promise<config.AppSettings>;

export function GetSkippedVersion():Promise<string>;

export function ImportConfig(arg1:string):Promise<void>;

export function ListAWSProfiles():Promise<Array<string>>;

export function SaveCluster(arg1:config.ClusterProfile):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SetActiveCluster(arg1:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function TestConnection(arg1:string):Promise<void>;
