import {
  ArrowCircleDown,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowsDownUp,
  Bell,
  Bookmark,
  CalendarX,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  Check,
  CheckCircle,
  CheckSquare,
  Circle,
  CircleNotch,
  Code,
  Copy,
  DownloadSimple,
  FileJs,
  Funnel,
  Gear,
  Globe,
  HardDrive,
  HardDrives,
  Info,
  Key,
  Lightning,
  MagnifyingGlass,
  Monitor,
  Moon,
  Palette,
  PaperPlaneTilt,
  Pause,
  PencilSimple,
  Play,
  Plus,
  Power,
  Pulse,
  RadioButton,
  ShieldSlash,
  ShieldWarning,
  Sparkle,
  Square,
  Stack,
  Sun,
  Tag,
  Timer,
  Trash,
  Trophy,
  UploadSimple,
  Warning,
  WarningCircle,
  X,
  XCircle,
  type Icon as PhosphorIconComponent,
} from "@phosphor-icons/react";

export const ICON_MAP = {
  "activity": Pulse,
  "alert-circle": WarningCircle,
  "alert-triangle": Warning,
  "arrow-down-circle": ArrowCircleDown,
  "arrow-up-down": ArrowsDownUp,
  "bar-chart": ChartBar,
  "bell": Bell,
  "bookmark": Bookmark,
  "calendar-x": CalendarX,
  "check": Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-down": CaretDown,
  "chevron-left": CaretLeft,
  "chevron-right": CaretRight,
  "chevron-up": CaretUp,
  "chevrons-left": CaretDoubleLeft,
  "chevrons-right": CaretDoubleRight,
  "circle": Circle,
  "code": Code,
  "copy": Copy,
  "download": DownloadSimple,
  "file-json": FileJs,
  "filter": Funnel,
  "globe": Globe,
  "hard-drive": HardDrive,
  "info": Info,
  "key": Key,
  "layers": Stack,
  "loader": CircleNotch,
  "monitor": Monitor,
  "moon": Moon,
  "palette": Palette,
  "pause": Pause,
  "pencil": PencilSimple,
  "play": Play,
  "plus": Plus,
  "power": Power,
  "radio": RadioButton,
  "refresh": ArrowClockwise,
  "rotate-ccw": ArrowCounterClockwise,
  "search": MagnifyingGlass,
  "send": PaperPlaneTilt,
  "server": HardDrives,
  "settings": Gear,
  "shield-alert": ShieldWarning,
  "shield-x": ShieldSlash,
  "sparkles": Sparkle,
  "square": Square,
  "sun": Sun,
  "tag": Tag,
  "timer": Timer,
  "timer-off": Timer,
  "trash": Trash,
  "trophy": Trophy,
  "upload": UploadSimple,
  "x": X,
  "x-circle": XCircle,
  "zap": Lightning,
} as const satisfies Record<string, PhosphorIconComponent>;

export type IconName = keyof typeof ICON_MAP;
